#!/bin/bash

go test github.com/mxxxxkxxxx/ogpproxy/config/...
go test github.com/mxxxxkxxxx/ogpproxy/console/...
go test github.com/mxxxxkxxxx/ogpproxy/controller/...
go test github.com/mxxxxkxxxx/ogpproxy/ogp/...
go test github.com/mxxxxkxxxx/ogpproxy/storage/...