#!/bin/bash

go test -v -race github.com/mxxxxkxxxx/ogpproxy/config/...
go test -v -race github.com/mxxxxkxxxx/ogpproxy/console/...
go test -v -race github.com/mxxxxkxxxx/ogpproxy/controller/...
go test -v -race github.com/mxxxxkxxxx/ogpproxy/ogp/...
go test -v -race github.com/mxxxxkxxxx/ogpproxy/storage/...